name: Deploy Application
run-name: ${{ github.actor }} is deploying application
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true
      version:
        description: 'version'
        default: 'master'
        required: true
      stage:
        description: 'stage'
        default: 'dev'
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Checkout [s118th-deploy] current branch
        uses: actions/checkout@v4
        with:
          path: deploy
      - name: Checkout [s118th] version [${{ inputs.version }}]
        uses: actions/checkout@v4
        with:
          repository: ro-ro-by/s118th
          ref: ${{ inputs.version }}
          token: ${{ secrets.REPO_TOKEN }}
          path: src

      - name: Build artifacts
        run: |
          chmod -R 777 src
          docker run -v ./src/app:/var/www/html/app -v ./dist:/var/www/html/build isxam/s118th-web-app-builder:latest bash deploy.sh --rm
      - name: Serverless stack deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "cd ./dist/src && serverless deploy --stage ${{ inputs.stage }}"
          entrypoint: /bin/sh
      - name: Upload assets to S3
        run: |
          aws s3 cp dist/src/public/assets s3://s118th-dev-web-app-assets/assets --recursive
